let obj = {
  'ref_area.label': [
    'Afghanistan',
    'United Arab Emirates',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Burundi',
    'Belgium',
    'Bulgaria',
    'Bosnia and Herzegovina',
    'Belarus',
    'Bolivia',
    'Brazil',
    'Brunei Darussalam',
    'Bhutan',
    'Botswana',
    'Canada',
    'Switzerland',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Curaçao',
    'Cyprus',
    'Czechia',
    'Germany',
    'Denmark',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'Spain',
    'Estonia',
    'Finland',
    'France',
    'Georgia',
    'Greece',
    'Honduras',
    'Croatia',
    'Hungary',
    'Indonesia',
    'Ireland',
    'Iran, Islamic Republic of',
    'Iceland',
    'Italy',
    'Jordan',
    'Japan',
    'Kazakhstan',
    'Kyrgyzstan',
    'Korea, Republic of',
    'Kosovo',
    'Saint Lucia',
    'Lithuania',
    'Luxembourg',
    'Latvia',
    'Moldova, Republic of',
    'Mexico',
    'North Macedonia',
    'Mali',
    'Malta',
    'Myanmar',
    'Montenegro',
    'Mongolia',
    'Montserrat',
    'Malaysia',
    'Netherlands',
    'Norway',
    'Oman',
    'Panama',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Paraguay',
    'Occupied Palestinian Territory',
    'Qatar',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'Saudi Arabia',
    'Singapore',
    'El Salvador',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Sweden',
    'Seychelles',
    'Thailand',
    'Trinidad and Tobago',
    'Türkiye',
    'Taiwan, China',
    'Tanzania, United Republic of',
    'Ukraine',
    'Uruguay',
    'United States',
    'Viet Nam',
    'World',
    'World: Low income',
    'World: Lower-middle income',
    'World: Upper-middle income',
    'World: High income',
    'Africa',
    'Americas',
    'Arab States',
    'Asia and the Pacific',
    'Europe and Central Asia',
    'South Africa',
    'Zambia',
  ],
  'indicator.label': [
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
    'SDG indicator 5.5.2 - Proportion of women in managerial positions (%)',
  ],
  'source.label': [
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Encuesta Permanente de Hogares (Urbano)',
    'LFS - Household Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'HIES - Enquête sur les Conditions de Vie des Ménages',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'HIES - Encuesta de Hogares',
    'HS - Pesquisa Nacional por Amostra de Domicílios Contínua',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey Report',
    'HS - Multi-Topic Household Survey',
    'LFS - Labour Force Survey',
    'LFS - Enquête sur la Population Active',
    'LFS - Encuesta Nacional de Empleo',
    'LFS - Gran Encuesta Integrada de Hogares',
    'LFS - Encuesta Continua de Empleo',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Sample Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - Encuesta Nacional Continua de Fuerza de Trabajo',
    'LFS - Encuesta Nacional de Empleo, Desempleo y SubEmpleo',
    'LFS - Labour Force Sample Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'HS - Encuesta Permanente de Hogares de Propósitos Múltiples',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - National Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - Employment and Unemployment Survey',
    'LFS - Labour Force Survey',
    'LFS - Sample Survey of Employment',
    'LFS - Employment and Unemployment Survey',
    'LFS - Economically Active Population Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Encuesta Nacional de Ocupación y Empleo',
    'LFS - Labour Force Survey',
    'LFS - Enquête Emploi Permanente Auprès des Ménages (EPAM)',
    'LFS - EU Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Encuesta de Mercado Laboral',
    'HS - Encuesta Nacional de Hogares',
    'LFS - Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'HS - Encuesta Permanente de Hogares Continua',
    'LFS - Labour Force Survey',
    'LFS - Labor Force Sample Survey',
    'LFS - EU Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Enquête sur la Population Active',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'HS - Encuesta de Hogares de Propósitos Múltiples',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - EU Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Continuous Sample Survey of the Population',
    'LFS - EU Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Labour Force Survey',
    'LFS - Encuesta Continua de Hogares',
    'LFS - Current Population Survey',
    'LFS - Labour Force Survey',
    'ILO - ILO Modelled Estimates',
    'ILO - ILO Modelled Estimates',
    'ILO - ILO Modelled Estimates',
    'ILO - ILO Modelled Estimates',
    'ILO - ILO Modelled Estimates',
    'ILO - ILO Modelled Estimates',
    'ILO - ILO Modelled Estimates',
    'ILO - ILO Modelled Estimates',
    'ILO - ILO Modelled Estimates',
    'ILO - ILO Modelled Estimates',
    'LFS - Quarterly Labour Force Survey',
    'LFS - Labour Force Survey',
  ],
  time: [
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
    '2020',
  ],
  obs_value: [
    4.9,
    17.7,
    33,
    28.1,
    40,
    32.8,
    35.5,
    33.8,
    34.5,
    41.3,
    25.1,
    50.5,
    30.1,
    36.8,
    36.5,
    32.7,
    56.7,
    35.8,
    33.1,
    27.4,
    34.9,
    59.4,
    51,
    24.2,
    27.8,
    28.9,
    27.9,
    38.1,
    39,
    6.8,
    35,
    37.5,
    37.5,
    35.5,
    36.1,
    29.3,
    40.1,
    28.4,
    39.2,
    32.6,
    36.3,
    18,
    38.6,
    27.3,
    60.3,
    13.3,
    41.1,
    47.4,
    15.6,
    17.5,
    60,
    37.9,
    26.3,
    46.9,
    42.3,
    38.4,
    20.6,
    null,
    28.2,
    27.8,
    32.1,
    49.8,
    50.2,
    24.9,
    26.2,
    34,
    25.9,
    45.8,
    34.7,
    53,
    43.3,
    35.7,
    37.8,
    21.7,
    10.7,
    35,
    45.7,
    33.4,
    15.4,
    37.2,
    46.7,
    31.5,
    35.5,
    40.1,
    42.3,
    41.8,
    39.2,
    46.7,
    18.2,
    30.5,
    27.9,
    40.7,
    38.7,
    41.1,
    26.3,
    28.3,
    21.9,
    19.2,
    32.1,
    35.9,
    20.8,
    39.7,
    11.1,
    23.3,
    35.8,
    31.4,
    45.9,
  ],
  'obs_status.label': [
    'Unreliable',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series',
    null,
    null,
    null,
    null,
    null,
    'Break in series',
    null,
    'Break in series',
    'Break in series',
    null,
    null,
    null,
    null,
    null,
    'Break in series',
    null,
    'Break in series',
    null,
    null,
    null,
    null,
    null,
    'Break in series',
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series',
    null,
    null,
    null,
    null,
    null,
    'Break in series',
    null,
    'Unreliable',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series',
    'Break in series',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series',
    null,
    'Break in series',
    'Break in series',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  'note_classif.label': [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  'note_indicator.label': [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series: Methodology revised',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series: Methodology revised',
    null,
    null,
    null,
    null,
    null,
    'Break in series: Methodology revised | Remarks: Data will be revised once more in May or June (for more information, refer to https://ec.europa.eu/eurostat/documents/10186/6246844/LFS-2020-Note-on-German-data.pdf)',
    null,
    'Break in series: Methodology revised',
    'Break in series: Methodology revised',
    null,
    null,
    null,
    null,
    null,
    'Break in series: Methodology revised | Remarks: ILO estimate based on the previous (13th ICLS) standards for time series comparability. Data are also available based on the new standards; refer to the Work Statistics - 19th ICLS (WORK) database.',
    null,
    'Break in series: Methodology revised',
    null,
    null,
    null,
    null,
    null,
    'Break in series: Methodology revised',
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series: Methodology revised',
    null,
    null,
    null,
    null,
    null,
    'Break in series: Methodology revised',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series: Methodology revised',
    'Break in series: Methodology revised',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Break in series: Methodology revised',
    null,
    'Break in series: Methodology revised',
    'Break in series: Methodology revised',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  'note_source.label': [
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing | Geographical coverage: Main cities or metropolitan areas',
    'Repository: ILO-STATISTICS - Micro data processing | Age coverage - maximum age: 75 years old',
    'Employment definition: Excluding own-use production workers | Geographical coverage: Total national, excluding overseas territories | Population coverage: Excluding both institutional population and armed forces and/or conscripts',
    'Repository: ILO-STATISTICS - Micro data processing | Age coverage - minimum age: Nonstandard minimum age',
    'Employment definition: Excluding own-use production workers | Data reference period: End of the year | Population coverage: Excluding both institutional population and armed forces and/or conscripts',
    'Repository: ILO-STATISTICS - Micro data processing | Age coverage - minimum age: 10 years old',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing | Employment definition: Excluding own-use production workers',
    'Repository: ILO-STATISTICS - Micro data processing | Age coverage - maximum age: 74 years old',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Geographical coverage: Total national, excluding some areas',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Employment definition: Including subsistence workers | Data reference period: Fourth quarter',
    'Repository: ILO-STATISTICS - Micro data processing | Age coverage - minimum age: Less than or equal to 9 years old',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing | Data reference period: Second quarter',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Employment definition: Excluding own-use production workers',
    'Employment definition: Excluding own-use production workers',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing | Age coverage - minimum age: Nonstandard minimum age',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing | Data reference period: First semester',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Employment definition: Excluding own-use production workers | Age coverage - maximum age: 64 years old',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Employment definition: Excluding own-use production workers | Population coverage: Excluding armed forces and/or conscripts | Age coverage - maximum age: 65 years old',
    'Repository: ILO-STATISTICS - Micro data processing | Data reference period: August',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Employment definition: Excluding own-use production workers',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Data reference period: June | Population coverage: Nationals, residents',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing | Employment definition: Excluding own-use production workers (although not measured separately)',
    'Repository: Eurostat special tabulation',
    'Repository: Eurostat special tabulation',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: Eurostat special tabulation',
    null,
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing | Age coverage - minimum age: 16 years old',
    'Repository: ILO-STATISTICS - Micro data processing',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Repository: ILO-STATISTICS - Micro data processing',
    'Repository: ILO-STATISTICS - Micro data processing',
  ],
};
